### ISSUE TITLE
README example incompatible with library

### ISSUE THREAD

**Issue by JoOkuma** [CellTrackingChallenge/py-ctcmetrics#13]
Hey @TimoK93 ,

I noticed the README example is incompatible with the current state of the python API.

Current README:

```python
from ctc_metrics import evaluate_sequence, validate_sequence

# Validate the sequence
res = validate_sequence("/ctc/train/challenge_x/01_RES")
print(res["Valid"])

# Evaluate the sequence
res = evaluate_sequence("/ctc/train/challenge_x/01_GT", "/ctc/train/challenge_x/01_RES")
print(res["DET"])
print(res["SEG"])
print(res["TRA"])
...
```

[evaluate_sequence](https://github.com/CellTrackingChallenge/py-ctcmetrics/blob/236f8fa365a2cca2d24dc0fd29d094248ab044a0/ctc_metrics/scripts/evaluate.py#L276-L281) takes first `res` and then `gt` and `res` needs the `TRA` path, [ref](https://github.com/CellTrackingChallenge/py-ctcmetrics/blob/236f8fa365a2cca2d24dc0fd29d094248ab044a0/ctc_metrics/scripts/evaluate.py#L95).

So, I'm currently using as:
```python
res = evaluate_sequence("/ctc/train/challenge_x/01_RES/TRA", "/ctc/train/challenge_x/01_GT")
```

**Comment by TimoK93** [comment]
Oh hello Jordao,

I got completely over the issue... Of course I'll fix it straight away. Thanks for the tip and sorry for leaving it for 2 months. Did the software help you with your work?

Regards,
Timo

**Comment by TimoK93** [comment]
Fixed with Commit https://github.com/CellTrackingChallenge/py-ctcmetrics/commit/06b2feaedfb7a797c6de8b7d039c7be5ee10705c

**Comment by JoOkuma** [comment]
Thanks, @TimoK93. That also happens to me all the time. GitHub sends too many e-mails.
